// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {ejsComment} from "./tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!vQQOROOOfOSO'#CbOnOSO'#CfOOOP'#Ca'#CaOOOP'#Ch'#ChOOOP'#Cj'#CjQQOROOOOOP,58|,58|OvOSO,58|OOOP,59Q,59QO{OSO,59QOOOP-E6h-E6hOOOP1G.h1G.hOOOP1G.l1G.l",
  stateData: "!V~OPTORTOSTOVPOZQO]SO~OWWOXVO~OWYOXXO~OX[O~OX]O~O]VZV~",
  goto: "n_PPPPP`dPPPdP`PhTTOUTROUQUORZU",
  nodeNames: "⚠ EjsComment Template HtmlComment Text EjsTag EjsExpression ExprStart Content TagEnd EjsBlock BlockStart EscapedTag LiteralStart",
  maxTerm: 15,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "5lRRZOutuv'av}t}!O(c!O!^t!^!_)o!_#Rt#R#S(c#S;'St;'S;=`'Z<%lOtR{ZWQSPOutuv!nv}t}!O%k!O!^t!^!_#Y!_#Rt#R#S%k#S;'St;'S;=`'Z<%lOtR!sVSPO!^t!^!_#Y!_!`t!`!a&]!a;'St;'S;=`'Z<%lOtR#_ZWQOqtqr$Qrutuv$rv}t}!O%k!O#Rt#R#S%k#S;'St;'S;=`'Z<%lOtQ$VXWQOu$Quv$rv}$Q}!O%X!O#R$Q#R#S%X#S;'S$Q;'S;=`%R<%lO$QQ$uSO!`$Q!a;'S$Q;'S;=`%R<%lO$QQ%UP;=`<%l$QQ%[TOu$Qv!`$Q!a;'S$Q;'S;=`%R<%lO$QR%pXSPOutuv&]v!^t!^!_#Y!_!`t!`!a&]!a;'St;'S;=`'Z<%lOtP&bTSPO!^&]!^!_&q!_;'S&];'S;=`'T<%lO&]P&tTOq&]ru&]v;'S&];'S;=`'T<%lO&]P'WP;=`<%l&]R'^P;=`<%ltR'fVSPO!^t!^!_#Y!_!`t!`!a'{!a;'St;'S;=`'Z<%lOtR(STXQSPO!^&]!^!_&q!_;'S&];'S;=`'T<%lO&]R(hXSPOutuv)Tv!^t!^!_#Y!_!`t!`!a&]!a;'St;'S;=`'Z<%lOtR)YVSPO!^&]!^!_&q!_!`&]!`!a'{!a;'S&];'S;=`'T<%lO&]R)tZWQOqtqr*grutuv2jv}t}!O%k!O#Rt#R#S%k#S;'St;'S;=`'Z<%lOtR*lXWQOu$Quv$rv}$Q}!O+X!O#R$Q#R#S%X#S;'S$Q;'S;=`%R<%lO$QR+[VOu$Qv}$Q}!O+q!O!`$Q!a;'S$Q;'S;=`%R<%lO$QR+vXWQOu+quv,cv}+q}!O0`!O#R+q#R#S/p#S;'S+q;'S;=`/j<%lO+qR,fVO}+q}!O,{!O!`+q!`!a.V!a;'S+q;'S;=`/j<%lO+qR-QXWQOu+quv,cv}+q}!O-m!O#R+q#R#S/p#S;'S+q;'S;=`/j<%lO+qR-pVOu+quv.Vv!`+q!`!a/_!a;'S+q;'S;=`/j<%lO+qP.YTO}.V}!O.i!O;'S.V;'S;=`/d<%lO.VP.lTO}.V}!O.{!O;'S.V;'S;=`/d<%lO.VP/OTO!`.V!`!a/_!a;'S.V;'S;=`/d<%lO.VP/dORPP/gP;=`<%l.VR/mP;=`<%l+qR/sXOu+quv.Vv}+q}!O,{!O!`+q!`!a.V!a;'S+q;'S;=`/j<%lO+qR0cXOu+quv.Vv}+q}!O1O!O!`+q!`!a.V!a;'S+q;'S;=`/j<%lO+qR1TZWQOu+quv,cv}+q}!O/p!O!`+q!`!a1v!a#R+q#R#S/p#S;'S+q;'S;=`/j<%lO+qR1}XWQRPOu$Quv$rv}$Q}!O%X!O#R$Q#R#S%X#S;'S$Q;'S;=`%R<%lO$QR2oZZPOu$Quv3bv}$Q}!O4U!O!_$Q!_!`4U!a#R$Q#R#S4x#S;'S$Q;'S;=`%R<%lO$QR3iXWQ]POu$Quv$rv}$Q}!O%X!O#R$Q#R#S%X#S;'S$Q;'S;=`%R<%lO$QR4]XWQVPOu$Quv$rv}$Q}!O%X!O#R$Q#R#S%X#S;'S$Q;'S;=`%R<%lO$QR5PXWQZPOu$Quv$rv}$Q}!O%X!O#R$Q#R#S%X#S;'S$Q;'S;=`%R<%lO$Q",
  tokenizers: [ejsComment, 0, 1],
  topRules: {"Template":[0,2]},
  tokenPrec: 48
})
