// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#`QQOPOOOcOQO'#C`OkOQO'#CdOsOQO'#CfOOOO'#C_'#C_OOOO'#Ch'#ChOOOO'#Cj'#CjQQOPOOOOOO,58z,58zO{OQO,58zOOOO,59O,59OO!QOQO,59OOOOO,59Q,59QO!VOQO,59QOOOO-E6h-E6hOOOO1G.f1G.fOOOO1G.j1G.jOOOO1G.l1G.l",
  stateData: "!b~OQUOTPOXQOZRO]TO~OUXOVWO~OUZOVYO~OU]OV[O~OV_O~OV`O~OVaO~O]TXZX~",
  goto: "n_PPP`dPPPdPdP`PhTUOVTSOVQVOR^V",
  nodeNames: "⚠ Template Text EjsTag EjsComment CommentStart Content TagEnd EjsExpression ExprStart EjsBlock BlockStart EscapedTag LiteralStart",
  maxTerm: 15,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: ".SRRZOutuv'Wv}t}!O(Y!O!^t!^!_)f!_#Rt#R#S(Y#S;'St;'S;=`'Q<%lOtR{ZUQQPOutuv!nv}t}!O%e!O!^t!^!_#Y!_#Rt#R#S%e#S;'St;'S;=`'Q<%lOtR!sVQPO!^t!^!_#Y!_!`t!`!a&V!a;'St;'S;=`'Q<%lOtR#_XUQOutuv#zv}t}!O%e!O#Rt#R#S%e#S;'St;'S;=`'Q<%lOtQ#}SO!`$Z!a;'S$Z;'S;=`%_<%lO$ZQ$`XUQOu$Zuv#zv}$Z}!O${!O#R$Z#R#S${#S;'S$Z;'S;=`%_<%lO$ZQ%OTOu$Zv!`$Z!a;'S$Z;'S;=`%_<%lO$ZQ%bP;=`<%l$ZR%jXQPOutuv&Vv!^t!^!_#Y!_!`t!`!a&V!a;'St;'S;=`'Q<%lOtP&[TQPO!^&V!^!_&k!_;'S&V;'S;=`&z<%lO&VP&nSOu&Vv;'S&V;'S;=`&z<%lO&VP&}P;=`<%l&VR'TP;=`<%ltR']VQPO!^t!^!_#Y!_!`t!`!a'r!a;'St;'S;=`'Q<%lOtR'yTVQQPO!^&V!^!_&k!_;'S&V;'S;=`&z<%lO&VR(_XQPOutuv(zv!^t!^!_#Y!_!`t!`!a&V!a;'St;'S;=`'Q<%lOtR)PVQPO!^&V!^!_&k!_!`&V!`!a'r!a;'S&V;'S;=`&z<%lO&VR)kXUQOutuv*Wv}t}!O%e!O#Rt#R#S%e#S;'St;'S;=`'Q<%lOtR*]]ZPOs$Zst+Utu$Zuv+xv}$Z}!O,l!O!_$Z!_!`,l!a#R$Z#R#S-`#S;'S$Z;'S;=`%_<%lO$ZR+]XUQTPOu$Zuv#zv}$Z}!O${!O#R$Z#R#S${#S;'S$Z;'S;=`%_<%lO$ZR,PXUQ]POu$Zuv#zv}$Z}!O${!O#R$Z#R#S${#S;'S$Z;'S;=`%_<%lO$ZR,sXUQXPOu$Zuv#zv}$Z}!O${!O#R$Z#R#S${#S;'S$Z;'S;=`%_<%lO$ZR-gXUQZPOu$Zuv#zv}$Z}!O${!O#R$Z#R#S${#S;'S$Z;'S;=`%_<%lO$Z",
  tokenizers: [0, 1],
  topRules: {"Template":[0,1]},
  tokenPrec: 58
})
