// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Template = 1,
  Text = 2,
  EjsTag = 3,
  EjsComment = 4,
  CommentStart = 5,
  Content = 6,
  TagEnd = 7,
  EjsExpression = 8,
  ExprStart = 9,
  EjsBlock = 10,
  BlockStart = 11,
  EscapedTag = 12,
  LiteralStart = 13
