// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  EjsComment = 1,
  Template = 2,
  HtmlComment = 3,
  Text = 4,
  EjsTag = 5,
  EjsExpression = 6,
  ExprStart = 7,
  Content = 8,
  TagEnd = 9,
  EjsBlock = 10,
  BlockStart = 11,
  EscapedTag = 12,
  LiteralStart = 13
