// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$zO]QPOOOOQO'#Cd'#CdOtQPO'#CgO|QPO'#CnOOQO'#Ct'#CtQOQPOOOOQO'#Ci'#CiO!TQPO'#ChO!YQPO'#CvOOQO,59R,59RO!bQPO,59RO!gQPO'#CwOOQO,59Y,59YO!oQPO,59YO]QPO,59SO!tQPO,59bO!|QPO,59bOOQO1G.m1G.mO#UQPO,59cO#]QPO,59cOOQO1G.t1G.tOOQO1G.n1G.nOOQO,59Z,59ZO#eQPO1G.|OOQO-E6m-E6mOOQO,59[,59[O#mQPO1G.}OOQO-E6n-E6nPwQPO'#CoP]QPO'#Cp",
  stateData: "#t~OgOSPOSQOS~OSSOTSOUSOVSOYQOaROiPO~OXXOiUO~O`[O~P]O^^O~O__OXjX~OXaO~O_bO`kX~O`dO~OiUOXja~O_gOXja~O`ka~P]O_jO`ka~OiUOXji~O`ki~P]O",
  goto: "!ulPPPPPPPPmPPmu}PPPPm!T!ZPPP!aP!o!r]SOR^bjmQWQVf_glXVQ_glQ`WRh`QcZRkcQTOQZRQe^VibjmRYQR]R",
  nodeNames: "⚠ LineComment BlockComment JsonText True False Null Number String } { Object Property PropertyName : , ] [ Array",
  maxTerm: 27,
  nodeProps: [
    ["isolate", -2,8,13,""],
    ["openedBy", 9,"{",16,"["],
    ["closedBy", 10,"}",17,"]"]
  ],
  skippedNodes: [0,1,2],
  repeatNodeCount: 2,
  tokenData: "+R~RbXY!ZYZ!Z]^!Zpq!Zrs!l|}%U}!O%Z!P!Q'T!Q!R%d!R![&r![!](y!}#O)O#P#Q)T#Y#Z)Y#b#c)w#h#i*`#o#p*w#q#r*|~!`Sg~XY!ZYZ!Z]^!Zpq!Z~!oWpq!lqr!lrs#Xs#O!l#O#P#^#P;'S!l;'S;=`%O<%lO!l~#^Oi~~#aXrs!l!P!Q!l#O#P!l#U#V!l#Y#Z!l#b#c!l#f#g!l#h#i!l#i#j#|~$PR!Q![$Y!c!i$Y#T#Z$Y~$]R!Q![$f!c!i$f#T#Z$f~$iR!Q![$r!c!i$r#T#Z$r~$uR!Q![!l!c!i!l#T#Z!l~%RP;=`<%l!l~%ZO_~~%^Q!Q!R%d!R![&r~%iRV~!O!P%r!g!h&W#X#Y&W~%uP!Q![%x~%}RV~!Q![%x!g!h&W#X#Y&W~&ZR{|&d}!O&d!Q![&j~&gP!Q![&j~&oPV~!Q![&j~&wSV~!O!P%r!Q![&r!g!h&W#X#Y&W~'WQz{'^!P!Q(_~'aTOz'^z{'p{;'S'^;'S;=`(X<%lO'^~'sTO!P'^!P!Q(S!Q;'S'^;'S;=`(X<%lO'^~(XOQ~~([P;=`<%l'^~(dTP~OY(_Z](_^;'S(_;'S;=`(s<%lO(_~(vP;=`<%l(_~)OO^~~)TOa~~)YO`~~)]P#T#U)`~)cP#`#a)f~)iP#g#h)l~)oP#X#Y)r~)wOT~~)zP#i#j)}~*QP#`#a*T~*WP#`#a*Z~*`OU~~*cP#f#g*f~*iP#i#j*l~*oP#X#Y*r~*wOS~~*|OY~~+ROX~",
  tokenizers: [0],
  topRules: {"JsonText":[0,3]},
  tokenPrec: 0
})
